"""Increase card_id_hash column length

Revision ID: aedc196cb8b8
Revises: 541aa6e4b17b
Create Date: 2025-02-21 19:16:18.965909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aedc196cb8b8'
down_revision: Union[str, None] = '541aa6e4b17b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('readers', 'card_id_hash',
               existing_type=mysql.VARCHAR(length=55),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('readers', 'dob',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('readers', 'dob',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.alter_column('readers', 'card_id_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=55),
               existing_nullable=False)
    # ### end Alembic commands ###
